# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6de533cc4b4cb9d8a49163bb9006a0abe45dcf52292ec2aa2633922d046933a919c41812c9a1a4d23b90375f9526f92c7389dcf5431f21569d221f121bb41dc5

test:
  secret_key_base: 34e57a511c6811e70fad3e6236c03f01e9a962ff1599f409e6ee418f7520067e644cee3576c58bab17ca257c20c3174e430a48ea96a13a54ffa95224fa262fc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
